docs/specification.md

cc @reza-curtmola
Reza pointed out that the design doc should clarify the RSL is a hash chain with no branching. This PR makes that change and adds the same clause to the policy namespace.

Clarify where we use hash chains

---

cmd/rsl.go
go.mod
internal/common/utils.go
internal/gitinterface/blob.go
internal/gitinterface/blob_test.go
internal/gitinterface/keys_test.go
internal/gitinterface/tree.go
internal/gitinterface/tree_test.go
internal/gitinterface/utils.go
internal/policy/policy.go
internal/signerverifier/dsse/dsse_test.go
internal/signerverifier/ed25519/ed25519_test.go
internal/tuf/tuf_test.go
rsl/rsl.go
rsl/rsl_test.go

Like #32, this moves some more parts of #27 into a standalone PR.
After this is good to go, we'll be focusing on the pure creation of TUF metadata bits. Side note: I have something based off sigstore/root-signing for generating the root metadata with multiple parties but we should discuss the UX.

More plumbing for policy

---

internal/gitinterface/commit.go
internal/gitinterface/keys.go
internal/gitinterface/keys_test.go

I suspect this accidentally stuck around back when I was still trying to use go-git for parsing the config. Alternatively, we can hold off and see if https://github.com/go-git/go-git/pull/760 is approved and we switch over to using go-git.

Remove repo parameter when crafting signing command

---

MAINTAINERS.txt

This PR adds a maintainers.txt file with names, emails, GitHub usernames, and affiliations.

Add list of maintainers

---

internal/gitinterface/tree.go
internal/gitinterface/tree_test.go
internal/rsl/rsl.go

Currently, we're using a zero hash for the tree ID for RSL entries. This is flagged as an error by Git, and visible when trying to push to some forges.

Use empty tree ID instead of zero for RSL commits

---

internal/common/common.go
internal/gitinterface/blob.go
internal/gitinterface/blob_test.go
internal/gitinterface/changes.go
internal/gitinterface/changes_test.go
internal/gitinterface/commit.go
internal/gitinterface/commit_test.go
internal/gitinterface/common_test.go
internal/policy/verify.go
internal/policy/verify_test.go

This breaks away some changes from #77.
Specifically, the changes here define a mechanism to get the list of changed file paths between two commits and the ability to derive this from an RSL entry for some namespace.
Note: I've included some test clean up as I noticed I was defining the same config, clock etc a bunch of times. I can submit that separately if needed. That's all in the last commit.

Support git diff

---

internal/cmd/policy/addrule/addrule.go
internal/cmd/policy/init/init.go
internal/cmd/policy/removerule/removerule.go
internal/cmd/rsl/remote/check/check.go
internal/cmd/rsl/remote/remote.go
internal/cmd/rsl/rsl.go
internal/cmd/trust/addpolicykey/addpolicykey.go
internal/cmd/trust/init/init.go
internal/cmd/trust/removepolicykey/removepolicykey.go
internal/cmd/verifyref/verifyref.go
internal/common/common.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/repository/rsl.go
internal/repository/rsl_test.go
internal/rsl/rsl.go
internal/rsl/rsl_test.go

This PR uses some of the semantics from #100 to check the remote RSL for updates. While the CLI command introduced here will be removed at a later date, the RSL update mechanism itself is plumbing for other sync workflows.
Part of #99.

Check remote RSL for updates

---

internal/cmd/common/common.go
internal/cmd/rsl/record/record.go
internal/repository/rsl.go
internal/repository/rsl_test.go

This adds an evaluation mode to gittuf and the first eval-only function, the ability to record RSL entries for non-latest commits. This is required to evaluate gittuf on existing repositories to simulate its behaviour over time.

Evaluation mode

---

internal/policy/helpers_test.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go

This commit introduces LoadStateForCommit, functionality that was previously embedded in verifyEntry. This enables reuse in the gittuf verify-commit workflow (#101).

Make commit policy finder reusable

---

internal/gitinterface/tag_test.go

I forgot to apply this in #113 after #112 was merged.

gitinterface: Fix gpg key load in test

---

internal/policy/test-data/targets-1
internal/policy/test-data/targets-2
internal/policy/verify.go
internal/policy/verify_test.go

So far, we were verifying each policy state internally. We weren't verifying that a new policy's root role is signed by keys trusted in the previous policy's root. This adds that check, and in the process, I think we solve the issue of not verifying RSL entry signatures for policy changes.

policy: Verify new policy against previous policy

---

README.md

gittuf is now part of the OpenSSF sandbox, following a vote by the TAC today: https://github.com/ossf/tac/pull/198

readme: Mention OpenSSF sandbox status

---

internal/cmd/root/root.go
internal/cmd/verifycommit/verifycommit.go
internal/gitinterface/tag.go
internal/policy/helpers_test.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/verify.go

Repurposing this PR to introduce verify-commit functionality. I have some draft code for verify-tag but it's a little more nuanced because a tag is both an object and a ref (so has RSL implications). For now, I think verify-commit is a go?
---
Original message:
WIP, needs more tests and clones some code also introduced in #82 and #100. Must only be merged after those.
TODO:
1. should we have a `gittuf policy add-key` or so that only adds a key somewhere without defining more granular policies? That'll allow for using gittuf only for simple signature checks.
2. should there be an optional --branch parameter for verify-commit so that it uses a specific policy state instead of all of them? Right now we have to use keys from all states, including revoked keys as we don't know when a commit …

Add verify-commit

---

internal/cmd/policy/addkey/addkey.go
internal/cmd/policy/policy.go
internal/policy/targets.go
internal/policy/targets_test.go
internal/repository/targets.go
internal/repository/targets_test.go

This allows users to simply add a public key to the specified policy file without using it in a delegation. This supports signature verification only scenarios.
Along with #101 and #122, this should resolve #15.

Add `gittuf policy add-key`

---

.github/workflows/ci.yml
.github/workflows/lint.yml

This PR adds Go 1.21.x to the CI workflows. It also bumps up the version of golangci-lint used, which isn't auto updated by dependabot.

ci: Bump Go and linter versions

---

internal/policy/helpers_test.go
internal/policy/policy.go
internal/repository/root.go
internal/repository/root_test.go
internal/signerverifier/dsse/dsse_test.go

Also updates import alias from "d" to "sslibdsse" for the upstream DSSE library. "d" was a mistake in retrospect.
Fixes: https://github.com/gittuf/gittuf/pull/114#discussion_r1327651423

Fix nil delegations

---

internal/gitinterface/sync.go
internal/gitinterface/sync_test.go
internal/gitinterface/utils.go
internal/repository/rsl_test.go

This PR introduces various fixes to gitinterface, some of which were previously seen in #115.
1. AbsoluteReference can now handle HEAD by resolving it to the target and returning that absolute path
2. Previously, there was some code to create the remote tracking ref for some ref, this has been broken out into a reusable component
3. Fetch had a trackRemote option to choose whether the fetch was for the remote tracker or not, this behavior has been updated to always fetch to the specified target ref (so `refs/heads/main:refs/heads/main`) _and_ the corresponding remote tracker
4. Some Fetch* tests missed a symbolic reference for HEAD, this is going to become an issue as we implement other sync interfaces alongside #134 
5. Some tests were using manual tmp dir handling, this has been updated …

Various fixes to gitinterface

---

internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/rsl/rsl.go
internal/rsl/rsl_test.go

See: #102
This PR also includes two trivial commits. The first removes earlier TODO statements regarding RSL entry signatures. This is now expected to be handled in the policy package (in fact the verification workflows are already in place for this, but annotations are not yet handled). The second updates the Entry and Annotation methods to use pointer receivers. I'm not sure why it wasn't already doing so.

rsl: Support annotations in RSL APIs

---

internal/cmd/clone/clone.go
internal/cmd/policy/policy.go
internal/cmd/root/root.go
internal/cmd/rsl/remote/push/push.go
internal/cmd/rsl/remote/remote.go
internal/cmd/trust/trust.go
internal/cmd/trustpolicy/remote/push/push.go
internal/cmd/trustpolicy/remote/remote.go
internal/common/common.go
internal/repository/common_test.go
internal/repository/policy.go
internal/repository/policy_test.go
internal/repository/rsl.go
internal/repository/rsl_test.go
internal/repository/sync.go
internal/repository/sync_test.go
internal/rsl/rsl.go

Based on https://github.com/gittuf/gittuf/pull/115#issuecomment-1756038262.
This PR adds a clone command that clones a repository from the specified remote location with its gittuf namespaces. Additionally, it implements a push command for the policy and RSL namespaces. The remote subcommand for `gittuf policy` and `gittuf trust` are shared in a new package.

Clone repository with gittuf namespaces and push RSL and policy namespaces to remote

---

internal/common/common.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/policy_test.go
internal/repository/rsl.go
internal/repository/rsl_test.go
internal/repository/verify_test.go
internal/rsl/rsl.go
internal/rsl/rsl_test.go

Closes #130
Renames:
Entry -> ~StandardEntry~ ReferenceEntry
Annotation -> AnnotationEntry
EntryType -> Entry
Some APIs like GetEntry... have been renamed depending on whether they return a standard entry or a generic entry.

Fix RSL terminology

---

internal/common/common.go
internal/policy/verify_test.go
internal/repository/verify_test.go

The `common` package has some helpers to create signed commits for use in tests. They used to default to the standard GPG key but some upcoming changes (#138) will use different keys to test for failure cases. This puts the invokers in control of the signing key to use.
The second change in this PR adds the ability to create test annotation entries, much like the existing standard entry creation function.

common: Updates to test helpers

---

.golangci.yml
internal/cmd/common/common.go
internal/cmd/policy/addkey/addkey.go
internal/cmd/policy/addrule/addrule.go
internal/cmd/policy/init/init.go
internal/cmd/policy/removerule/removerule.go
internal/cmd/rsl/annotate/annotate.go
internal/cmd/rsl/record/record.go
internal/cmd/trust/addpolicykey/addpolicykey.go
internal/cmd/trust/init/init.go
internal/cmd/trust/removepolicykey/removepolicykey.go
internal/cmd/verifycommit/verifycommit.go
internal/cmd/verifytag/verifytag.go
internal/gitinterface/blob_test.go
internal/gitinterface/changes.go
internal/gitinterface/changes_test.go
internal/gitinterface/utils.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/repository/sync.go
internal/rsl/rsl.go
internal/rsl/rsl_test.go
main.go

Blocked by #137.
In #137, we broke out golangci-lint's config into a separate file. This PR adds more checks to this config and submits fixes flagged by the new checks. This can only be reviewed after #137 (and a rebase) to get the actual diff.

Add linters

---

internal/policy/policy.go
internal/policy/policy_test.go
internal/rsl/rsl.go
internal/rsl/rsl_test.go

This PR has gittuf treat the RSL and policy with zero hashes as uninitialized. This fixes the issue where `gittuf trust init` is unable to proceed again after being invoked without a signing key specified in the user's git configuration.
Also see #147

Fix trust command issue with signing key not specified

---

internal/gitinterface/sync.go

- Double initial capacity of reSpecs slice in Fetch for higher efficiency in append operations

Double Initial Capacity of reSpecs Slice in Fetch

---

CHANGELOG.md
internal/rsl/rsl.go
internal/rsl/rsl_test.go

Part of #138
This PR adds functions to find the latest unskipped RSL reference entry for the specified ref.

rsl: Add functions to find unskipped entries

---

internal/policy/policy.go

We only have a generic rsl.Entry when looking up a policy state directly by ID. This is a less common case, and we needn't type-assert a reference entry when we know we have one. This moves the guard over to only be invoked where it's needed.

policy: Update RSL types when loading policies

---

internal/gitinterface/blob.go
internal/gitinterface/blob_test.go
internal/gitinterface/changes.go
internal/gitinterface/changes_test.go
internal/gitinterface/commit.go
internal/gitinterface/commit_test.go
internal/gitinterface/log.go
internal/gitinterface/log_test.go
internal/gitinterface/tag.go
internal/gitinterface/tag_test.go
internal/gitinterface/tree.go
internal/gitinterface/tree_test.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/rsl.go
internal/rsl/rsl.go
internal/rsl/rsl_test.go

This allows us to perform additional checks in future such as whether an object is replaced by a replace ref. It also makes it easier to switch between go-git and another mechanism to invoke Git, such as directly using the binary.
See: #133 
Related: #2

*: Route GetObject requests through gitinterface

---

internal/common/common.go
internal/gitinterface/changes_test.go
internal/gitinterface/commit.go
internal/gitinterface/commit_test.go
internal/gitinterface/log_test.go

- Make CreateCommitObject support merge commits, with multiple parent hashes
- Changed other files to use an array of parent hashes instead of a single hash

Make CreateCommitObject Support Merge Commits

---

.github/workflows/ci.yml
.github/workflows/lint.yml

This can happen commonly for dependabot and other PRs that are opened from inside the same repo.

Restrict push workflows to main to prevent double running CI 

---

internal/cmd/common/common.go
internal/cmd/policy/addkey/addkey.go
internal/cmd/policy/addrule/addrule.go
internal/cmd/policy/init/init.go
internal/cmd/policy/removerule/removerule.go
internal/cmd/rsl/annotate/annotate.go
internal/cmd/rsl/record/record.go
internal/cmd/trust/addpolicykey/addpolicykey.go
internal/cmd/trust/init/init.go
internal/cmd/trust/removepolicykey/removepolicykey.go

This PR addresses #147 where we'd like to ensure that we can sign git commits before we touch anything in the repository. 
With this change, invoking `gittuf rsl record` will cause gittuf to check that a signing key is specified and usable before continuing. For now, only `record.go` is modified - we can move this up to `rsl.go` if we want all rsl commands to inherit this check, as well as add this check to other commands if need be.

Check that git signing is viable

---

LICENSE

Per #128, this PR updates the license file's header. The same header is used in the gittuf GitHub Action (https://github.com/gittuf/gittuf-installer/blob/main/LICENSE).

Update license header

---

internal/repository/targets.go

Fixes a panic in creating delegated policy  metadata, discovered by @bradcush.

repository: Fix panic when storing delegated policy

---

docs/design-document.md

The reference entry structure was generalized to support non-commit targets, useful for tags especially. This commit updates the design document to reflect the change.
#120 and #122

design: Fix RSL reference entry structure

---

internal/policy/verify.go

This PR adds a check for cases where a key is technically trusted to sign for some namespace but it can only be used with gittuf policies, not Git objects. We have this check elsewhere.
Long term, this check can be pulled out because the signing method aligns with SSH keys. So I suggest we add this check in now and strip them out when we have support for Git <-> SSH keys.

policy: Account for non Git signing keys in verify

---

internal/repository/sync.go
internal/repository/sync_test.go

repository: Fix clone not handling trailing slashes in repository path.

---

internal/common/common.go

We have two copies of these vars in the repo. One is in `common`, the other in `gitinterface`. We can't avoid defining the second one as its a dependency for `common`. I'm also leaning against defining it just once in `gitinterface` as `common` basically just holds test specific helpers / data, so it's the more natural home. This PR exports the `common` one for other packages to use.

common: Export test config and clock

---

internal/gitinterface/log_test.go

- Clarified TODO for GetCommitsBetweenRange, passing the commit id's in reverse order should change the result of the function.

Clarify TODO for GetCommitsBetweenRange

---

docs/design-document.md

This is a first pass at noting how a gittuf user signing an RSL entry on behalf of a non gittuf user can authenticate the user.
At this point, the doc doesn't talk about the data model for how the RSL entry is signed (if any changes are needed) and how the evidence is logged in the repository. My inclination is to use the attestation model being developed in other open PRs. I think that bit can wait until later, once we have that ready to go, and in the meantime the change in this PR can flesh out the general mechanism.

design: Flesh out on-behalf-of workflows

---

internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/verify.go
internal/repository/verify_test.go

This updates the repository package to check that the current state of the tested ref matches the latest RSL entry.

Check that the tip of a ref matches latest corresponding RSL entry

---

.github/ISSUE_TEMPLATE/issue.yml

Fix rendering issue in bug report template, add blank issue template that is not immediately obvious in the GitHub new issue workflow. This also unifies the checkbox for CoC acceptance that is currently only in the bug report.

github: Update issue templates

---

internal/repository/rsl.go
internal/repository/rsl_test.go

`gittuf rsl record` would blindly create RSL entries when instructed, even if the content was identical to the latest unskipped entry for the ref in question. This PR prevents duplicate RSL entries.

repository: Prevent duplicate RSL entries

---

internal/cmd/addhooks/addhooks.go
internal/cmd/addhooks/prepush.go
internal/cmd/clone/clone.go
internal/cmd/root/root.go
internal/repository/hook.go
internal/repository/hook_test.go

Manage hooks as described in: #158 
Added `UpdateHook` functionality. There doesn't seem to be support for managing hooks in go-git (https://github.com/src-d/go-git/issues?q=is%3Aissue+is%3Aopen+hook) 
~~Unit test currently breaks as the `conf.Core.Worktree` value is not populated when creating a repo with `PlainInit`. Any input appreciated.~~ done
Add following tests / features before merging: 
* make sure hook is executable
* do not overwrite hook script unless force
Further considerations:
* `gittuf rsl record HEAD` should not add a record when executed multiple times. We need a new issue for this.

implement gittuf add-hooks to configure pre-push hook

---

.github/workflows/lint.yml

This saves us the trouble of manually updating golangci-lint's version.

lint: Use latest version by default

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/issue.yml

In the default issue type, we currently have "Issue: Issue" because of the template's name. This one also skips auto-assigning me to the issue, which we want in bug reports for immediate triage.

github: Minor issue template nits

---

internal/policy/helpers_test.go
internal/policy/policy_test.go

- Fixed the createTestStateWithDelegatedPolicies, so that when it is used in conjunction with createTestRepository, and when the state is commited, it can pass the verification check.
- Currently the test will not pass, but when PR 219 is merged, it should work

Fixed the createTestStateWithDelegatedPolicies

---

internal/cmd/trust/addrootkey/addrootkey.go
internal/cmd/trust/removerootkey/removerootkey.go
internal/cmd/trust/trust.go
internal/policy/root.go
internal/policy/root_test.go
internal/repository/helpers_test.go
internal/repository/repository_test.go
internal/repository/root.go
internal/repository/root_test.go
internal/repository/sync_test.go
internal/repository/targets_test.go

- Added functionality to cmd to add and remove root keys from, which needs a key already in the root to allow adding or removing keys from the root.
- Partially fixes issue https://github.com/gittuf/gittuf/issues/117

Added add and remove root keys to cmd

---

internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/repository/targets.go

Prior to this PR, gittuf performed self-contained verification for each policy state. The idea was to validate all metadata in the policy state was signed by the right keys etc. Unfortunately, this doesn't work well because the exact delegating role to use is unclear as multiple roles can delegate to the same role with different keys + threshold requirements. This can only be reconciled when verifying for a specific path / namespace, which the self contained verification does not have. This has been previously encountered in TUF (https://github.com/theupdateframework/specification/issues/19, https://github.com/theupdateframework/specification/issues/214, https://github.com/theupdateframework/python-tuf/issues/660) and this PR modifies `state.Verify` in gittuf to avoid the issue.

Refactor state.Verify() to avoid promiscuous delegations

---

internal/cmd/verifyref/verifyref.go
internal/repository/verify.go
internal/repository/verify_test.go

Flips cmd flags for `gittuf verify-ref` to perform full verification by default. Until we implement #245, this is a safer default.

*: Make full verification default in verify-ref

---

internal/repository/helpers_test.go
internal/repository/targets_test.go

- Removed createTestRepositoryWithTargets in favor of createTestRepositoryWithPolicy, since both have similar functions.
- With the embeded key bytes in helpers_test, we do not need the return value of createTestRepositoryWithTargets
- Addresses https://github.com/gittuf/gittuf/pull/225#discussion_r1437251654

Removed createTestRepositoryWithTargets in favor of createTestRepositoryWithPolicy

---

go.mod
go.sum
internal/gitinterface/commit_test.go
internal/gitinterface/keys.go

I discovered a bug in the SSH signature verification introduced in #253. This fixes it!
~Draft until #257 is merged.~
I didn't dive into the specific issue entirely (time constraints), but my thinking is it had to do with how we were decoding SSH signature fields and passing it to crypto/ssh for verification. Switching to the sshsig library fixed it right away, and signature verification compatibility aligns with `git verify-commit` now when we specify trusted ssh keys using `gpg.ssh.allowedsigners`. I would like to dive into the specific bug in the previous implementation in the near future.

Fix SSH signature verification

---

internal/policy/policy.go
internal/repository/targets.go
internal/repository/targets_test.go

Detect if a policy role was already expanded during DFS.
Also added a check to ensure a delegated role or rule isn't called "root". Most of the diff in the tests is in moving an existing test into a t.Run block to add another checking for the invalid name.

Detect cycles in delegations DFS, make "root" invalid policy file name

---

internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go

This is a first step at making verifyEntry more efficient. We now only check for file protection rules if the policy state has at least one in any targets role.
Also, this commit sets constants for the Git reference and file rule schemes.

policy: Apply file rules only if they exist

---

docs/cli/gittuf_policy.md
docs/cli/gittuf_policy_sign.md
internal/cmd/policy/policy.go
internal/cmd/policy/sign/sign.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/repository/helpers_test.go
internal/repository/root.go
internal/repository/root_test.go
internal/repository/targets.go
internal/repository/targets_test.go

Fixes minor bugs in root key management subcommands. Also adds gittuf policy sign to add a signature to existing policy file.
Blocked by #264, #268, and #269.

Fix bugs in root public key tracking

---

docs/cli/gittuf_verify-ref.md
internal/cmd/verifyref/verifyref.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/helpers_test.go
internal/repository/sync.go
internal/repository/verify.go
internal/repository/verify_test.go

This PR adds a `--from-entry` flag to verify a ref from a certain RSL entry onwards.

Add from flag to verify-ref

---

LICENSE

It was pointed out to me (cc @06kellyjac) that the LICENSE file must include the full text of the Apache 2.0 license. The text we previously included is meant to license specific files rather than the project as a whole.
Note that this does not change how gittuf is licensed.

Fix Apache 2.0 license file

---

internal/gitinterface/tag_test.go

Removes unused parameter to make the linter happy.

gitinterface: Remove unused parameter

---

CONTRIBUTING.md

Doing my homework for https://github.com/ossf/DevRel-community/issues/35 required a bit of spelunking because there wasn't mention of either the Slack channel or the monthly community meetings in either README.md or CONTRIBUTING.md (first two places I looked).
This is a simple PR to just add a reference to those in, in order to help the next person.

Expand CONTRIBUTING.md to cover Slack + community meetings

---

internal/cmd/addhooks/prepush.go

Noticed a missing SPDX header in `prepush.go`.

Add missing SPDX header

---

docs/cli/gittuf_policy.md
docs/cli/gittuf_policy_update-rule.md
internal/cmd/policy/policy.go
internal/cmd/policy/updaterule/updaterule.go
internal/policy/helpers_test.go
internal/policy/policy_test.go
internal/policy/targets.go
internal/policy/targets_test.go
internal/repository/targets.go
internal/repository/targets_test.go

Earlier, add-rule was also (silently) the command to update an existing rule. This PR makes these separate flows as a first step in making rule names unique in policy. Now, we can check during add-rule that a rule with the same name doesn't already exist.
Part of #304.

Split up add and update rule flows

---

internal/common/set/set.go
internal/policy/helpers_test.go
internal/policy/policy.go
internal/repository/targets.go

This allows us to avoid diamond delegations in policy and provide more guardrails to users.

Make rule names unique in gittuf policy

---

internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/root.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/root_test.go

Since rule names are unique across all metadata in a policy state, we don't have to worry about diamond delegations. So, we can verify all signatures on policy metadata as well as check if some file is not reachable. With this change, FindVerifiersForPath no longer needs to verify delegated metadata signatures.
Separately, state.Verify is now limited to internal consistency checks. So, it verifies that root keys in the state match, followed by checking all the targets role signatures as discussed above.
Finally, LoadCurrentState now inspects all policy states to verify root role on each state using the previous one. The very first one is still TOFU, but this can be bootstrapped using other mechanisms.
Blocked by #304.

Refactor policy state verification

---

docs/cli/gittuf_policy_add-rule.md
docs/cli/gittuf_policy_update-rule.md
docs/cli/gittuf_trust.md
docs/cli/gittuf_trust_update-policy-threshold.md
internal/cmd/policy/addrule/addrule.go
internal/cmd/policy/updaterule/updaterule.go
internal/cmd/trust/trust.go
internal/cmd/trust/updatepolicythreshold/updatepolicythreshold.go
internal/policy/helpers_test.go
internal/policy/policy_test.go
internal/policy/root.go
internal/policy/targets.go
internal/policy/targets_test.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/helpers_test.go
internal/repository/root.go
internal/repository/root_test.go
internal/repository/targets.go
internal/repository/targets_test.go

This PR adds support for specifying thresholds in gittuf rules. For full threshold support, we need #260 / #45 merged / resolved, so that the top level targets role can meet the threshold in the refs/gittuf/policy.
As a start, though, this can be used to specify thresholds in rules that are expected to be met using RSL entry signatures / commit signatures / attestations (#254).

Add support for setting and verifying threshold for rules / delegations

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/release.yml
docs/get-started.md
go.mod

Trying to fix the CI failures in #317, I think it may be because of go.mod's Go version. Note that in the process, I'm adding 1.22.x to the CI workflow.

Support Go 1.22.x

---

internal/policy/verify.go
internal/policy/verify_test.go

- Adds an extra check that verifies that the target hash of the tag object is the same as its corresponding RSL entry's target hash.

Add extra verification when verifying tags

---

.github/workflows/scorecard.yml

This PR enables OpenSSF scorecard for the gittuf repository. This fulfills a requirement we have to meet as part of the OpenSSF. I've configured the defaults from the GitHub marketplace.

Enable OpenSSF Scorecard

---

internal/gitinterface/keys.go
internal/gitinterface/keys_test.go
internal/testartifacts/gitconfig.go
internal/testartifacts/testdata/gitconfigs/config-4
internal/testartifacts/testdata/gitconfigs/config-5

Now, user.signingkey is required only when the signing format is ssh. I suspect we can loosen this too?

gitinterface: Make user.signingkey optional

---

docs/cli/gittuf_dev_authorize.md
internal/attestations/authorization.go
internal/attestations/authorization_test.go
internal/cmd/dev/authorize/authorize.go
internal/gitinterface/tree.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/attestations.go
internal/repository/attestations_test.go

This PR updates the authorization attestation to use the merge tree as the target for the attestation. This better allows for ahead of time merges. For example, if the main branch has commit A and feature branch has commit B, previously, we required the merge to be a fast forward merge in the context of the authorization attestation. Specifically, the attestation recorded commit B as the target. Now, the target is the result of `git merge-tree <commitA> <commitB>`.

Switch authorizations to use merge tree target

---

internal/repository/sync.go

This is needed when actual recovery flows have happened.

repository: Verify full history on clone

---

docs/cli/gittuf_dev.md
docs/cli/gittuf_dev_attest-github.md
go.mod
go.sum
internal/attestations/attestations.go
internal/attestations/attestations_test.go
internal/attestations/github.go
internal/cmd/dev/attestgithub/attestgithub.go
internal/cmd/dev/dev.go
internal/repository/attestations.go

In developer mode, this records a GitHub PR's information as an attestation (using the GitHub API).
Note: I want to examine and incorporate work by @neilnaveen from #320 as well.

Store GitHub PR data as an attestation

---

.github/workflows/gittuf-rsl-main.yml
.github/workflows/gittuf-rsl-non-main.yml
.github/workflows/gittuf-verify.yml

This avoids failures of gittuf workflows for forks that may not have the gittuf refs.

ci: Run gittuf workflows only on gittuf/gittuf

---

internal/cmd/common/common.go
internal/cmd/policy/addkey/addkey.go
internal/cmd/policy/addrule/addrule.go
internal/cmd/policy/init/init.go
internal/cmd/policy/persistent/persistent.go
internal/cmd/policy/policy.go
internal/cmd/policy/removerule/removerule.go
internal/cmd/policy/sign/sign.go
internal/cmd/policy/updaterule/updaterule.go
internal/cmd/trust/addpolicykey/addpolicykey.go
internal/cmd/trust/addrootkey/addrootkey.go
internal/cmd/trust/init/init.go
internal/cmd/trust/persistent/persistent.go
internal/cmd/trust/removepolicykey/removepolicykey.go
internal/cmd/trust/removerootkey/removerootkey.go
internal/cmd/trust/sign/sign.go
internal/cmd/trust/trust.go
internal/cmd/trust/updatepolicythreshold/updatepolicythreshold.go
internal/cmd/trust/updaterootthreshold/updaterootthreshold.go

Invoking gittuf's policy commands that require a signing key without the `-k` flag to specify said signing key does not raise an error.
Currently, this check is performed by setting an attribute on the flag via cobra. Unfortunately, it appears that disabling this requirement for subcommands that do not need a signing key (i.e. `list-rules`) _also_ disables the flag for subcommands that _do_ need it.
This PR recreates the required flag check in the `CheckIfSigningViable` function.
A minor note: As this is done in PreRunE, the signing key flag check will run before other flag checks. Run `gittuf policy add-rule` without any flags before and after this PR change to see what I mean. Unsure if we care about this.

Rework policy signing-key flag check

---

docs/get-started.md

fixes #360
* changes key type `ecdsa` to `rsa` (the former resulted in an unsupported format on macos)
* add `-N` option to not prompt for an encryption password and to store key in plain text (encrypted keys are currently not supported)

doc: quick fix keygen snippet in get-started.md

---

docs/get-started.md

Now that we're using gittuf on its own repository, it might be a good idea to mention verification of the repository by end-users in the gettting started doc.

docs: Mention dogfooding in get-started.md

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/release.yml

This enables caching on the `lint`, `docs`, `release`, and `tests` actions on CI.
Ubuntu and macOS appear to benefit greatly while Windows not so much.

ci: Enable caching on actions

---

internal/gitinterface/common.go

This PR fixes CI on Windows failing due to a test in `gitinterface` by manually working with the temporary directory.
Addresses #407.

gitinterface: Fix test failing on Windows

---

internal/policy/policy_test.go
internal/policy/root.go
internal/policy/root_test.go
internal/policy/targets.go
internal/policy/targets_test.go
internal/repository/root.go
internal/repository/root_test.go
internal/repository/targets.go
internal/repository/targets_test.go
internal/signerverifier/dsse/dsse_test.go
internal/tuf/tuf.go
internal/tuf/tuf_test.go

The original root and targets metadata schemas were taken directly from the TUF specification. As such, they include fields that we don't use in gittuf.
Removed Fields:
1. SpecVersion: this field identifies the version of the TUF specification the metadata conforms to. We don't conform to the TUF specification.
2. ConsistentSnapshot: this boolean field indicates if the repository uses consistent snapshots as defined in the TUF specification. We don't use this (and in fact we don't use snapshot metadata at all as the RSL effectively serves the snapshot role).
3. Version: this field is an incrementing integer that identifies the version of the metadata for the specific role. In TUF, this is used to ensure we have a consistent set of metadata via the snapshot role. As before, the RSL gives …

Remove TUF fields that don't apply to gittuf

---

internal/signerverifier/dsse/dsse_test.go
internal/signerverifier/ssh/ssh.go
internal/signerverifier/ssh/ssh_test.go
internal/tuf/tuf_test.go

Previously, ssh `Key` satisfied both the `dsse.Verifier` interface and served as TUF metadata key container. Unfortunately, it didn't seem feasible to wire up the key container with the current TUF metadata implementation, which uses `SSlibKey`.
This commit re-designs the ssh key implementation to use SSlibKey as key container and a separate Verifier for verification.
See https://github.com/gittuf/gittuf/pull/429#issuecomment-2151588628 for more detailed design considerations.
Change details:
* Add an SSHKeyTypeConstant
* Rename Import to NewKeyFromFile
* Replace ssh Key with ssh Verifier, which satisfies the dsse.Verifier interface, but is otherwise a black box (no key details exposed).
* Change NewKeyFromFile to return an SSlibKey, to be included in TUF metadata.
* Add …

Re-design ssh Key as Verifier only

---

.gitattributes

From: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
They render as follows now:
So we can still opt in to see specific changes, but IMO this makes reviewing bigger changes easier.

Ignore generated CLI docs in PR diff

---

internal/repository/hook.go
internal/repository/hook_test.go

path.Join only uses `/`.
filepath.Join will use `/` or `\` depending on the OS
Might be messing with Windows compatibility. (though not sure)

Replace path.Join -> filepath.Join

---

.github/workflows/get-started-tests.yml
Makefile

We should run the `get-started` CI tests if there are changes to the `get-started.md` doc or testing data.

ci: Enable `get-started` tester on certain docs changes

---

internal/repository/root.go

We're incorrectly returning nil when err != nil.

Fix err return

---

.github/workflows/ci.yml
.test_ignore.txt

This PR prevents files that don't need / have tests from cluttering up our testing coverage results. By default, it looks like go includes everything in coverage, including things like `docs/cli`, which is irrelevant. This allows us to select what should be included.
This will probably need improvement for windows due to the use of `grep`...

Change how test coverage is calculated

---

.test_ignore.txt
docs/cli/gittuf_dev_rsl-record.md
docs/cli/gittuf_rsl_record.md
docs/cli/gittuf_verify-ref.md
internal/cmd/dev/rslrecordat/rslrecordat.go
internal/cmd/rsl/record/record.go
internal/cmd/verifyref/verifyref.go
internal/repository/options/rsl/rsl.go
internal/repository/options/verify/verify.go
internal/repository/rsl.go
internal/repository/rsl_test.go
internal/repository/sync.go
internal/repository/verify.go
internal/repository/verify_test.go

Closes #413 
This PR makes two changes. First, when recording an entry in the RSL, it supports the src ref name being different from the dst ref name. For example, `git push origin local-branch-name:remote-branch-name` updates `remote-branch-name` on origin with the tip of `local-branch-name`. So, the RSL entry for this push must record `remote-branch-name` as the ref name updated, which is what everyone else sees, and use `local-branch-name` as the target ID.
Second, the verification workflow now accepts an optional `--remote-ref-name` flag. When this is set, the workflow uses the remote ref name to identify and verify the relevant RSL entries, but finally uses the local ref name to check that the tip matches. We need this for the following case:
```
git fetch origin …
```

Support the local and remote ref names being different

---

internal/git-remote-gittuf/ssh.go

We had a mistaken assumption that if the remote didn't already have the RSL ref, the oldTip variable would be set to zero.

transport: Fix discovery of old RSL tip on remote

---

docs/transport/transport.md

This PR adds a document to explain the purpose of the transport, as well as how to use it.
See #464.

transport: Add a transport info doc

---

.goreleaser.yml
CHANGELOG.md

We don't have release assets for v0.5.0 due to a breaking change in goreleaser. I propose we go directly to v0.5.1 with binaries, I don't want us to re-tag nor do I want to have binaries that are not signed by the release workflow's identity.

Fix goreleaser and prepare v0.5.1

---

.github/workflows/ubuntu-2204.yml
internal/gitinterface/changes_test.go
internal/gitinterface/tree.go
internal/gitinterface/tree_test.go
internal/gitinterface/utils.go
internal/repository/attestations_test.go

This allows us to support Git < 2.36, needed for users still on Ubuntu 22.04.
Closes #434

Support older Git versions

---

.github/workflows/gittuf-rsl-main.yml
.github/workflows/gittuf-rsl-non-main.yml

Summary:
* Set key permission to 600 for SSH signing key
* Use setup-gitsign workflow instead of installing from source
* Bump gittuf-installer to new release

ci: Update gittuf record workflows

---

docs/cli/gittuf_policy.md
docs/cli/gittuf_policy_reorder-rules.md
internal/cmd/policy/policy.go
internal/cmd/policy/reorderrules/reorderrules.go
internal/common/set/set.go
internal/policy/targets.go
internal/policy/targets_test.go
internal/repository/targets.go
internal/repository/targets_test.go

1. Add a function ReorderDelegations() to handle rule reordering from backend
2. Add a command ```gittuf policy reorder-rules [flags]``` to reorder rules from CLI

Add functions and a command for reorder rules in a policy file

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/get-started-tests.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/ubuntu-2204.yml

This PR bumps the go version for our tests workflow to `1.23`.
Most notably, this changes our testing coverage results:
`1.22` (https://github.com/gittuf/gittuf/actions/runs/10819478695/job/30017444897):
```
Run go test -covermode=atomic `go list ./... | grep -v -f .test_ignore.txt`
github.com/gittuf/gittuf		coverage: 0.0% of statements
ok  	github.com/gittuf/gittuf/internal/attestations	0.267s	coverage: 27.4% of statements
ok  	github.com/gittuf/gittuf/internal/cmd/common	0.037s	coverage: 2.3% of statements
github.com/gittuf/gittuf/internal/common/set		coverage: 0.0% of statements
github.com/gittuf/gittuf/internal/common		coverage: 0.0% of statements
ok  	github.com/gittuf/gittuf/internal/display	0.060s	coverage: 15.5% of statements
ok  	github.com/gittuf/gittuf/internal/gitinterface …
```

ci: Bump go version to 1.23

---

docs/cli/gittuf_rsl_remote.md
docs/cli/gittuf_rsl_remote_reconcile.md
internal/cmd/rsl/remote/check/check.go
internal/cmd/rsl/remote/reconcile/reconcile.go
internal/cmd/rsl/remote/remote.go
internal/gitinterface/commit.go
internal/gitinterface/commit_test.go
internal/gitinterface/remote.go
internal/gitinterface/remote_test.go
internal/repository/rsl.go
internal/repository/rsl_test.go

When checking the status of the remote RSL against the local RSL, we must not use the transport, as that will also update the local RSL (in addition to the remote tracker). With this commit, a separate temporary remote is created and used.
Part of #525

Add reconciliation workflow to update local RSL against remote RSL

---

internal/attestations/attestations.go
internal/common/common.go
internal/display/rsl.go
internal/display/rsl_test.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/repository/attestations.go
internal/repository/rsl.go
internal/rsl/cache_test.go
internal/rsl/options.go
internal/rsl/rsl.go
internal/rsl/rsl_test.go

This commit adds a uint64 Number field to RSL entries. This allows us to determine the ordering of distinct RSL entries, enabling optimizations such as knowing which policy to use for an entry without always walking the RSL.
The implementation maintains backwards compatibility, so the numbering can start from whenever this is enabled. This is made easy by the fact that we can guarantee gittuf is updated everywhere it is currently used.

rsl: Add incrementing number to RSL entry

---

internal/git-remote-gittuf/README.md
internal/git-remote-gittuf/curl.go
internal/git-remote-gittuf/helpers.go
internal/git-remote-gittuf/main.go
internal/git-remote-gittuf/split.go
internal/git-remote-gittuf/ssh.go

This is a first pass at cleaning up git-remote-gittuf (I reckon we need another couple with different focuses).
This incorporates some suggestions from @lukpueh to simplify the states the transport can be and how we implement them.

Rework git-remote-gittuf to be cleaner and easier to maintain

---

.github/workflows/codeql.yml
.github/workflows/coverage.yml
.github/workflows/get-started-tests.yml
.github/workflows/lint.yml
.github/workflows/scorecard.yml
.github/workflows/ubuntu-2204.yml

This PR prevents most CI from running when there are only changes to the `docs` directory.
Turns out we needed to use `**` instead of just `*`: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

ci: Don't run CI on changes to only docs

---

internal/attestations/searcher.go
internal/attestations/searcher_test.go
internal/policy/searcher.go
internal/policy/searcher_test.go
internal/policy/verify.go

This commit adds Searcher interfaces for the policy and attestations refs, which are used by VerifyRelativeForRef.

policy, attestations: Add Searcher interfaces

---

internal/attestations/authorization.go
internal/attestations/authorization_test.go
internal/attestations/github.go
internal/attestations/github_test.go
internal/cmd/common/common.go
internal/policy/helpers_test.go
internal/policy/policy.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/repository/attestations.go
internal/repository/attestations_test.go
internal/repository/root.go
internal/repository/root_test.go
internal/repository/targets.go
internal/signerverifier/dsse/dsse.go
internal/signerverifier/dsse/dsse_test.go
internal/third_party/go-securesystemslib/README.md
internal/third_party/go-securesystemslib/dsse/envelope.go
internal/third_party/go-securesystemslib/dsse/sign.go
internal/third_party/go-securesystemslib/dsse/signerverifier.go
internal/third_party/go-securesystemslib/dsse/verify.go
internal/third_party/go-securesystemslib/signerverifier/signerverifier.go
internal/tuf/tuf_test.go

This PR prepares #524 by vendoring the dsse library and adding support for signature extensions.

Vendor go-sslib/dsse and add support for setting a signature extension

---

internal/gitinterface/commit_test.go
internal/policy/policy_test.go

Increased coverage from ~72% -> 79.7% on policy.go
* Changed test state creation from one Policy to creating test state with delegated policies to increase coverage
* Added a case for TestStateKeys where one test runs as a state with delegated policies and the other with the state having only the root - to increase test coverage on the state.PublicKeys() method.

increasing policy.go test coverage

---

Makefile

This PR fixes building from source on Windows platforms, by changing how the `CGO_ENABLED` var is set.

build: Update Makefile to work on Windows

---

docs/cli/gittuf_trust.md
docs/cli/gittuf_trust_update-policy-threshold.md
docs/cli/gittuf_trust_update-root-threshold.md
internal/cmd/trust/updatepolicythreshold/updatepolicythreshold.go
internal/cmd/trust/updaterootthreshold/updaterootthreshold.go

This PR removes the devmode requirement for updating the thresholds for the root of trust and policy.

cmd: Drop devmode requirement for root and policy thresholds

---

CHANGELOG.md

This PR adds the changelog for and prepares `v0.6.1`.

Prepare v0.6.1 release

---

.goreleaser.yml
internal/git-remote-gittuf/README.md

Add git-remote-gittuf to releaser. We don't need to add it to brew install just yet, but it'll make piloting the transport easier with folks who don't work with Go / have older OS-es with versions of Go we can't use.

release: Add transport to goreleaser

---

internal/gitinterface/commit.go
internal/gitinterface/signature.go
internal/gitinterface/tag.go
internal/signerverifier/signerverifier.go

Closes #448 
I ran into an import cycle when I was trying something and decided to change this. Signing flow needs changing still, and possibly careful testing to ensure we're compatible.
Edit: I don't know if we want to change the signing flow: we're working off key bytes and it's used more for tests at the moment.

Use signerverifier/ssh for git signing / verifying

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/coverage.yml
.github/workflows/get-started-tests.yml
.github/workflows/lint.yml
.github/workflows/scorecard.yml
.github/workflows/ubuntu-2204.yml

This PR prevents triggering most of CI on changes to only Markdown files.

ci: Don't run most of CI on changes to Markdown files

---

.gitignore

I sometimes vendor via `go mod vendor` when I need to debug something. I don't want to accidentally check it in...

gitignore: Ignore vendor directory

---

debug/Dockerfile.Git_2_34_1
debug/README.md

This should make life easier when debugging on Git 2.34.1.

debug: Add Dockerfile for debugging gittuf on Git 2.34.1

---

.github/workflows/get-started-tests-policy-v02.yml
experimental/gittuf/root.go
experimental/gittuf/root_test.go
experimental/gittuf/targets.go
experimental/gittuf/targets_test.go
internal/policy/helpers_test.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/root.go
internal/policy/targets.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/tuf/migrations/migrations.go
internal/tuf/tuf.go
internal/tuf/v02/helpers_test.go
internal/tuf/v02/root.go
internal/tuf/v02/root_test.go
internal/tuf/v02/targets.go
internal/tuf/v02/targets_test.go
internal/tuf/v02/tuf.go

This commit introduces v02 of policy metadata schemas for root and targets files. The biggest change is the introduction of the Person principal type. Additionally, this commit also sets v02 as the default and sets up migrations for existing v01 metadata.

tuf, policy, gittuf: Add v02 of policy metadata

---

docs/cli/gittuf_policy.md
docs/cli/gittuf_policy_list-principals.md
experimental/gittuf/policy.go
internal/cmd/policy/listprincipals/listprincipals.go
internal/cmd/policy/policy.go
internal/policy/list.go
internal/policy/list_test.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/tuf/tuf.go
internal/tuf/v01/tuf.go
internal/tuf/v02/tuf.go
internal/tuf/v02/tuf_test.go

adds a list-principals sub command. This is needed for #639 to be usable.
Specifically, #639 makes it so you add keys / persons first and then add rules referencing those keys / persons. This command is required to pick up on key IDs or principal IDs in that metadata when adding a rule.

policy, cmd: Add list-principals sub command

---

experimental/gittuf/attestations.go
experimental/gittuf/options/github/github.go
internal/cmd/dev/addgithubapproval/addgithubapproval.go
internal/cmd/dev/attestgithub/attestgithub.go
internal/cmd/dev/dismissgithubapproval/dismissgithubapproval.go

This makes setting the token a bit cleaner with the gittuf API used in the github app.

gittuf: Expose GitHub token as an opt

---

internal/git-remote-gittuf/curl.go
internal/git-remote-gittuf/helpers.go
internal/git-remote-gittuf/ssh.go

This fixes some transient hanging in the transport. The transport doesn't always write all the tips as haves, there seems to be a heuristic that's triggered depending on the number of locally available branches. This was causing the fetch to hang indefinitely.

transport: Write gittuf haves explicitly

---

experimental/gittuf/attestations.go
experimental/gittuf/root.go
experimental/gittuf/rsl.go
experimental/gittuf/targets.go
internal/cmd/common/common.go
internal/cmd/dev/authorize/authorize.go
internal/cmd/policy/addkey/addkey.go
internal/cmd/policy/addperson/addperson.go
internal/cmd/policy/addrule/addrule.go
internal/cmd/policy/init/init.go
internal/cmd/policy/removerule/removerule.go
internal/cmd/policy/reorderrules/reorderrules.go
internal/cmd/policy/sign/sign.go
internal/cmd/policy/updaterule/updaterule.go
internal/cmd/rsl/annotate/annotate.go
internal/cmd/rsl/record/record.go
internal/cmd/rsl/skiprewritten/skiprewritten.go
internal/cmd/trust/addgithubappkey/addgithubappkey.go
internal/cmd/trust/addpolicykey/addpolicykey.go
internal/cmd/trust/addrootkey/addrootkey.go
internal/cmd/trust/disablegithubappapprovals/disablegithubappapprovals.go
internal/cmd/trust/enablegithubappapprovals/enablegithubappapprovals.go
internal/cmd/trust/init/init.go
internal/cmd/trust/removegithubappkey/removegithubappkey.go
internal/cmd/trust/removepolicykey/removepolicykey.go
internal/cmd/trust/removerootkey/removerootkey.go
internal/cmd/trust/sign/sign.go
internal/cmd/trust/updatepolicythreshold/updatepolicythreshold.go
internal/cmd/trust/updaterootthreshold/updaterootthreshold.go

This PR moves the `CheckIfSigningViable` check to the gittuf API and updates the signing key argument check as well.
Closes #633

*: Move signing checks around

---

internal/git-remote-gittuf/curl.go
internal/git-remote-gittuf/ssh.go

Adding a duplicate have <sha> or want <sha> can cause the packfile negotiation to hang. Also, sometimes, not announcing a have for a gittuf ref but requesting a want for it can cause a hang. This fixes these scenarios by tracking all wants and haves, and adding gittuf wants only when it's not a duplicate, and always annoucing gittuf haves.

transport: Some wants / haves negotiation fixes

---

experimental/gittuf/verify.go
internal/gitinterface/utils.go
internal/policy/searcher.go
internal/policy/verify.go
internal/policy/verify_test.go

~Depends on #439~
~A bunch of comments for verify-mergeable were left there, will cross reference.~
I've applied the comments in threads inline for discussion. The idea of verify-mergeable is to be able to say "this PR can be merged as it has reached the required number of approvals" or "this PR can be merged as long as the merge is by someone with approval powers". I want to plug this into gittuf/github-app to add checkruns to a repository.

Add verify-mergeable

---

internal/policy/helpers_test.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go

We have some policy state specific tasks that need to happen only once and can be consolidated as part of a generic preprocessing flow.

policy: Consolidate some preprocessing passes

---

internal/git-remote-gittuf/ssh.go

Turns out we weren't writing this flush packet if there weren't gittuf refs on the remote, causing the transport to lock up.
Closes #634.

transport: Add missing flush packet

---

docs/cli/gittuf.md
docs/cli/gittuf_verify-mergeable.md
internal/cmd/root/root.go
internal/cmd/verifymergeable/verifymergeable.go
internal/policy/searcher.go
internal/policy/verify.go
internal/policy/verify_test.go

1. VerifyMergeable was incorrectly returning an error when no verifiers were found (for an unprotected base branch).
2. Policy's searcher interface was also returning the wrong error when the latest policy or attestation entry was not found.
3. A verify-mergeable command has been added to simplify debugging.

Various policy fixes

---

docs/cli/gittuf_rsl_record.md
experimental/gittuf/options/rsl/rsl.go
experimental/gittuf/rsl.go
experimental/gittuf/rsl_test.go
internal/cmd/rsl/record/record.go
internal/git-remote-gittuf/curl.go
internal/git-remote-gittuf/ssh.go

The RSL entry creation flow checks to see if the latest entry for the reference being pushed has the same target ID as the proposed new entry. This check should be optional, depending on how the entry is created. When created using the "gittuf rsl record" command, the check should be performed by default. But when created using the git-remote-gittuf transport, the check is superfluous: the push is happening and an extra entry recording the push happened is better. This also speeds up the RSL entry creation for a new branch via the transport, as looking for an existing RSL entry for the branch in question is expensive (the entire RSL history must be checked).

Add control for RSL duplicate check

---

.github/workflows/ubuntu-2204.yml

Looks like there was an update to Git 2.34: https://launchpad.net/ubuntu/+source/git/1:2.34.1-1ubuntu1.12
This PR fixes the broken workflow for the older Git version.

ci: Fix Git 2.34 run

---

internal/tuf/migrations/migrations.go

The PR adding support for global rules in the metadata missed adding the migration between v01 and v02.

tuf: Add globalRules to migrator

---

docs/cli/gittuf_trust.md
docs/cli/gittuf_trust_add-github-app.md
docs/cli/gittuf_trust_remove-github-app.md
experimental/gittuf/attestations.go
experimental/gittuf/root.go
experimental/gittuf/root_test.go
internal/cmd/trust/addgithubapp/addgithubapp.go
internal/cmd/trust/removegithubapp/removegithubapp.go
internal/cmd/trust/trust.go
internal/policy/helpers_test.go
internal/policy/policy.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/tuf/tuf.go
internal/tuf/v01/root.go
internal/tuf/v01/root_test.go
internal/tuf/v02/root.go
internal/tuf/v02/root_test.go

gittuf has a companion app for GitHub that can record attestations for pull request reviews. Previously, the app was identified by its signing key. This commit adds initial support for naming the app, with an eye towards eventually supporting attestations from multiple apps.

*: Initial support for naming for gittuf app

---

docs/cli/gittuf_verify-mergeable.md
experimental/gittuf/options/verifymergeable/verifymergeable.go
experimental/gittuf/verify.go
internal/cmd/verifymergeable/verifymergeable.go
internal/policy/verify.go
internal/policy/verify_test.go

This is a stab at not using the RSL for the feature ref when checking for mergeability. We need this for the github app case.

policy: Add VerifyMergeableForCommit

---

experimental/gittuf/attestations_test.go
experimental/gittuf/rsl_test.go
experimental/gittuf/sync_test.go
internal/attestations/attestations.go
internal/attestations/attestations_test.go
internal/cache/cache.go
internal/common/common.go
internal/gitinterface/changes_test.go
internal/gitinterface/commit_test.go
internal/gitinterface/log_test.go
internal/gitinterface/object_test.go
internal/gitinterface/references_test.go
internal/gitinterface/sync_test.go
internal/gitinterface/tag_test.go
internal/gitinterface/tree.go
internal/gitinterface/tree_test.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/rsl/rsl_test.go

This cleans up tree builder to accept entry types. It also refactors how blobs are managed to (in future) add support for custom permission bits for blob entries. This is necessary for #758 pieces.

gitinterface: Support types for tree entries

---

docs/cli/gittuf_rsl_annotate.md
docs/cli/gittuf_rsl_record.md
docs/get-started.md
docs/testing/tester-expected-unix.txt
docs/testing/tester-expected-win.txt
experimental/gittuf/attestations_test.go
experimental/gittuf/options/rsl/rsl.go
experimental/gittuf/rsl.go
experimental/gittuf/rsl_test.go
experimental/gittuf/sync_test.go
internal/cmd/rsl/annotate/annotate.go
internal/cmd/rsl/record/record.go
internal/cmd/sync/sync.go
internal/git-remote-gittuf/curl.go
internal/git-remote-gittuf/ssh.go

This tries to straighten out how RSL update syncing and propagation interact with each other.

Reconcile sync and propagation workflows

---

internal/cmd/attest/github/pullrequest/pullrequest.go

This fixes a bug with the new gittuf attest github pull-request command.

cmd: Fix base URL use for GitHub PR attestation

---

internal/gitinterface/object.go
internal/gitinterface/object_test.go

This PR adds functionality to gitinterface to fetch the size of objects from the repository - primarily intended for the API exposed in the Lua sandbox.
~~WIP, possibly adding more functionality.~~

gitinterface: Add support for fetching object size

---

internal/tuf/v01/root.go
internal/tuf/v01/root_test.go
internal/tuf/v02/root.go
internal/tuf/v02/root_test.go

This PR adds a propagation directive to propagate the `policy-staging` ref from a controller repository, in addition to `policy`.
Related: See #825.

tuf: Add propagation directive for policy-staging when adding controller

---

CITATION.bib

Opening this as a draft until the full details are available.
This PR adds the citation for the gittuf paper as presented in NDSS 2025.

gittuf paper citation.bib file

---

internal/policy/helpers_test.go
internal/policy/policy.go

This PR tracks the RSL entry used to load policy in the state.

policy: Track RSL entry used to load policy state

---

internal/policy/policy.go
internal/policy/policy_test.go

This adds controller metadata verification to state.Verify.

policy: Verify controller metadata with upstream

---

internal/signerverifier/ssh/ssh.go

Possible fix for test race condition.

signerverifier: Avoid race condition in test key cleanup

---

docs/gaps/5/README.md
docs/gaps/6/README.md
docs/gaps/README.md

Adds app / code review tool attestations as an extension doc after some discussions with @wlynch re https://github.com/gittuf/github-app.

docs: Add app / code review tool attestations

---

internal/tuf/v01/root.go
internal/tuf/v01/root_test.go
internal/tuf/v02/root.go
internal/tuf/v02/root_test.go

Reverts gittuf/gittuf#882, in favor of the policy reconciliation workflow: #825.

Revert "tuf: Add propagation directive for policy-staging when adding controller"

---

docs/cli/gittuf_trust_list-global-rules.md
docs/cli/gittuf_trust_list-hooks.md
experimental/gittuf/policy.go
experimental/gittuf/root.go
experimental/gittuf/root_test.go
internal/cmd/trust/listglobalrules/listglobalrules.go
internal/cmd/trust/listhooks/listhooks.go

This PR addresses various nits in the `ListGlobalRules` and `ListHooks` functions (e.g. move to `experimental/gittuf/policy.go` and support passing in the policy ref to inspect).

*: Organize various list functions

---

.goreleaser.yml

This PR adds the configuration to goreleaser needed to automatically open pull requests on the WinGet repository for publishing gittuf releases.
I based this off of how the folks at the Minder project do their releases: https://github.com/mindersec/minder/blob/main/.goreleaser.yaml
This PR has two prerequisites before it can be merged:
1. Obtain a PAT from the OpenSSF for the openssf-robot account (working on this...) EDIT: see https://github.com/ossf/tac/issues/466 
3. Fork the winget-pkgs repo under the gittuf org so that we can have the workflow automatically generate PRs for the upstream winget-pkgs repo.

ci: Enable goreleaser publishing to winget

---

docs/cli/gittuf_trust_add-hook.md
experimental/gittuf/root.go
experimental/gittuf/root_test.go
internal/cmd/trust/addhook/addhook.go
internal/cmd/trust/listhooks/listhooks.go
internal/luasandbox/luasandbox.go
internal/luasandbox/options/luasandbox/luasandbox.go
internal/tuf/tuf.go
internal/tuf/v01/root.go
internal/tuf/v01/root_test.go
internal/tuf/v02/root.go
internal/tuf/v02/root_test.go

This PR updates the hooks metadata to remove the `modules` field and add the `timeout` field. After the edits to the PR that added the Lua Sandbox (#859), it doesn't make too much sense to keep the `modules` field and allow arbitrary module loading. We should make the `timeout` configurable for users though, I think.
While this is a breaking change, we haven't released gittuf with these changes so I think we should be OK here.

*: Remove hook modules field and add timeout

---

experimental/gittuf/keys.go
internal/signerverifier/git/git.go
internal/signerverifier/git/git_test.go

This PR adds an API to `signerverifier` to automagically load a signing key based on a repository's Git configuration and exposes said API in `experimental/gittuf`.

Add git config signer

---

experimental/gittuf/hook.go
experimental/gittuf/hook_test.go
experimental/gittuf/options/hooks/hooks.go
internal/luasandbox/luasandbox.go
internal/luasandbox/options/luasandbox/luasandbox.go
internal/testartifacts/testdata/scripts/hello.lua

This PR adds functionality to the gittuf API that enables the invocation of gittuf hooks encoded in the metadata. This is used in gittuf-git to invoke hooks at the proper stage.
~~Blocked by #813.~~
~~Blocked by #839.~~

[GUPPIEs] *: Add hook invocation

---

experimental/gittuf/repository.go

The --verbose cmd flag was broken in a prior commit as we were setting the default level to info in the gittuf package.

gittuf: Fix verbose cmd flag

---

.github/workflows/run-demo.yml

This PR has the gittuf demo run on the code introduced by a PR, instead of just the latest released version.

ci: Update gittuf demo to use version from PR

---

CHANGELOG.md
README.md

This PR prepares gittuf `v0.10.0`.
Blocked by:
- #860 
- #892 
- #638 
- #765 
EDIT: We can likely defer these features to the next release, since one can already add these to the metadata with the currently-merged PRs.

Prepare v0.10.0

---

docs/development/gittuf-metadata.md

This PR adds a document that describes the steps needed to inspect the metadata that underpins a repository's gittuf policy.

docs: Add doc on how to inspect gittuf's metadata

---

internal/common/set/set.go
internal/common/set/set_test.go

Changed the value type of the underlying set type from `bool` to `struct{}` to minimize size.
Added logic to handle `nil` structure contents and `nil` values for operations.
Added unit tests for sets.

Change underlying set content type and added unit tests

---

README.md
main.go

This PR adds a link to the OpenSSF Slack workspace to help people new to the project reach out, as well as fixes a small typo in `main.go`.

Add slack link and fix typo

---

.goreleaser.yml

This should fix this deprecation notice in the releasing workflow:
`DEPRECATED:  archives.format  should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info`
See  https://goreleaser.com/deprecations/#archivesformat.

ci: Update deprecated format specification in goreleaser

---

.github/workflows/gittuf-verify.yml
README.md

This PR adds a gittuf verification workflow to merges to the main branch.
Note that there may be a race condition here. The action may fail before the app has a chance to record the attestation + RSL entry for the merge. I suggest we add this and monitor it.

ci: Add gittuf verification on main branch

---

CONTRIBUTING.md
SECURITY_INSIGHTS.yml

This PR adds a dependencies policy to gittuf, based off of the policy of Kubescape: https://github.com/kubescape/kubescape/blob/master/docs/environment-dependencies-policy.md.

Add dependencies policy to gittuf

---

internal/attestations/github/v01/pr_test.go

This PR significantly improves test coverage for the `pr.go` file in the `/internal/attestations/github/v01` package.  
It increases the test coverage from **0% to 70%**, ensuring more comprehensive validation of the GitHub attestations logic.
Fixes part of [#463](https://github.com/gittuf/gittuf/issues/463) – Testing Coverage
- **File path:** `./internal/attestations/github/v01/pr.go`
```sh
go test -coverprofile=coverage.out ./internal/attestations/github/v01/
go tool cover -html=coverage.out -o coverage.html

Improve-test-cov for pr.go in /internal/attestations/github/v01/

---

docs/cli/gittuf_trust_add-propagation-directive.md
experimental/gittuf/root.go
experimental/gittuf/root_test.go
experimental/gittuf/rsl_test.go
internal/cmd/trust/addpropagationdirective/addpropagationdirective.go
internal/gitinterface/tree.go
internal/gitinterface/tree_test.go
internal/rsl/rsl.go
internal/tuf/tuf.go
internal/tuf/v01/root.go
internal/tuf/v01/root_test.go
internal/tuf/v02/root.go

This PR adds support for propagating a specific path in the upstream reference in the upstream repository. Previously, propagation would copy the entire upstream reference root tree, but now a specific subtree path can be specified.

*: Propagate specific path in upstream repository

---

internal/gitinterface/tree_test.go

Fixes the CI failure on Windows where path names are too long from #1013.

gitinterface: Fix propagation test filenames too long on Windows

---

docs/cli/main.go

This pull request addresses part of the issue related to enhancing CLI command documentation by adding a `Long` description to the `gendoc` Cobra command.
The `Long` field provides a more detailed explanation of what the command does, including its purpose (generating Markdown documentation for all gittuf CLI commands), its usage, and the default output behavior. This improves the CLI's usability and clarity for both new and experienced users.
This update is part of the broader effort to improve the documentation coverage for all Cobra commands in the gittuf project.

Add Long description to gendoc Cobra command

---

.github/workflows/ci-locale.yml
.github/workflows/ci.yml
.github/workflows/get-started-tests.yml
.github/workflows/ubuntu-2204.yml
experimental/gittuf/rsl.go
go.mod
internal/cmd/trust/listhooks/listhooks.go
internal/policy/policy.go
internal/policy/policy_test.go
internal/policy/verify.go
internal/policy/verify_test.go
internal/tuf/v01/root.go
internal/tuf/v01/root_test.go
internal/tuf/v02/root.go
internal/tuf/v02/root_test.go

This is a first pass at pre-computing the policy controller graph and propagating all changes _flatly_.

*: Propagate policy exhaustively without nesting

---

docs/cli/gittuf_attest_github.md
internal/cmd/attest/github/github.go

This pull request adds a detailed Long description to the 'github' sub-command under 'attest' in the gittuf CLI.
The description outlines the purpose of this parent command and its subcommands for attesting to GitHub-specific actions such as pull request approvals and dismissals.
This enhancement is part of the ongoing effort to improve Cobra command documentation throughout the gittuf project.

docs: add Long description to attest github commandGitHub long doc

---

docs/cli/gittuf_attest_github_pull-request.md
internal/cmd/attest/github/pullrequest/pullrequest.go

This pull request adds a Long description to the 'pull-request' command in the gittuf CLI.
The Long field documents how the command creates attestations for GitHub pull requests, helping verify merge origins and improve traceability in gittuf-secured repositories.
This is part of the overall effort to enhance Cobra command documentation in the gittuf project.

docs: add Long description to pull-request Cobra commandPull request long doc

---

docs/cli/gittuf.md
docs/cli/gittuf_policy_list-principals.md
docs/cli/gittuf_policy_list-rules.md
docs/cli/gittuf_policy_remove-key.md
docs/cli/gittuf_policy_remove-person.md
docs/cli/gittuf_policy_remove-rule.md
docs/cli/gittuf_policy_reorder-rules.md
docs/cli/gittuf_policy_sign.md
docs/cli/gittuf_policy_update-rule.md
internal/cmd/policy/listprincipals/listprincipals.go
internal/cmd/policy/listrules/listrules.go
internal/cmd/policy/removekey/removekey.go
internal/cmd/policy/removeperson/removeperson.go
internal/cmd/policy/removerule/removerule.go
internal/cmd/policy/reorderrules/reorderrules.go
internal/cmd/policy/sign/sign.go
internal/cmd/policy/updaterule/updaterule.go
internal/cmd/root/root.go

' This pull request adds comprehensive long descriptions to multiple cobra commands in the gittuf CLI.
' These enhanced descriptions provide better context and guidance for users about the purpose and usage
' of each command. This improves the overall usability and documentation quality of the gittuf CLI tool.
'
' Changes include:
' - Adding detailed explanations for commands such as removeperson, removerule, reorderrules, sign, tui, updaterule, root, and others.
' - Clarifying flag purposes and command behavior in the long descriptions.
' - Ensuring consistency across all cobra commands' help texts.
'
' This documentation update aims to assist both new and experienced users in effectively managing their
' security policies with gittuf.

Docs: Add detailed long descriptions for cobra commands in gittuf CLI

---

docs/cli/gittuf_policy_add-person.md
internal/cmd/policy/addperson/addperson.go

This PR adds a detailed Long description to the 'add-person' command in the gittuf CLI.
The description outlines the purpose of the command, the required and optional flags, supported key and identity formats, and the integration with RSL and trust policy structures.
This update is part of the ongoing effort to fully document all Cobra commands.

docs: add Long description to add-person command Doc add person long desc

---

docs/cli/gittuf_policy_add-key.md
internal/cmd/policy/addkey/addkey.go

This PR enhances the 'add-key' command in the gittuf CLI by adding a detailed Long description.
The update clarifies the command’s purpose, supported key formats, required flags, and its integration with the trust policy framework and RSL system.
This update is part of the ongoing effort to fully document all Cobra commands.

docs: add Long description to add-key commandDoc add key long desc

---

docs/cli/gittuf_dev_populate-cache.md
internal/cmd/dev/populatecache/populatecache.go

This PR adds a Long description to the 'populate-cache' developer command in the gittuf CLI.
The description explains its purpose for development use and the requirement of enabling developer mode by setting the appropriate environment variable.
This change contributes to the complete documentation of all Cobra commands.

docs: add Long description to populate-cache commandDoc populate cache

---

docs/cli/gittuf_dev.md
internal/cmd/dev/dev.go

This pull request adds a Long description to the 'dev' command group in the gittuf CLI.
The Long description explains the purpose and cautions associated with using development-only commands, including the requirement to set an environment variable to proceed.
This is part of an effort to fully document all Cobra commands in the repository.

docs: add Long description to dev Cobra commandDev long doc

---

docs/cli/gittuf_rsl.md
docs/cli/gittuf_rsl_propagate.md
docs/cli/gittuf_trust.md
docs/cli/gittuf_trust_add-controller-repository.md
docs/cli/gittuf_trust_add-global-rule.md
docs/cli/gittuf_trust_add-network-repository.md
docs/cli/gittuf_trust_add-propagation-directive.md
docs/cli/gittuf_trust_make-controller.md
docs/cli/gittuf_trust_remove-global-rule.md
docs/cli/gittuf_trust_remove-propagation-directive.md
docs/cli/gittuf_trust_update-global-rule.md
experimental/gittuf/cache_test.go
experimental/gittuf/root.go
experimental/gittuf/root_test.go
experimental/gittuf/rsl.go
experimental/gittuf/rsl_test.go
internal/cmd/rsl/propagate/propagate.go
internal/cmd/trust/addcontrollerrepository/addcontrollerrepository.go
internal/cmd/trust/addglobalrule/addglobalrule.go
internal/cmd/trust/addnetworkrepository/addnetworkrepository.go
internal/cmd/trust/addpropagationdirective/addpropagationdirective.go
internal/cmd/trust/makecontroller/makecontroller.go
internal/cmd/trust/removeglobalrule/removeglobalrule.go
internal/cmd/trust/removepropagationdirective/removepropagationdirective.go
internal/cmd/trust/updateglobalrule/updateglobalrule.go
internal/policy/helpers_test.go
internal/policy/verify_test.go

This PR:
1. Removes unneeded devmode checks and env var settings that weren't removed when moving functionality out of devmode before.
2. Moves multi-repo functionality and global rules out of devmode.
I think that both items are candidates to move out of devmode, but I can split the PR into two parts if we want to hold off on promoting more functionality.

Move functionality out of devmode

---

docs/cli/gittuf_attest_authorize.md
internal/cmd/attest/authorize/authorize.go

This PR adds detailed Long descriptions to the 'apply' and 'authorize' subcommands under the 'attest' command.
- apply: explains applying local attestations and optionally pushing to remote
- authorize: explains adding or revoking reference authorizations
These additions improve the help output for users.

docs: add Long descriptions to attest apply and authorize subcommands

---

docs/get-started.md

Looks like a mention of gittuf in alpha in the getting started doc wasn't updated to reflect beta status.

docs: Update getting started doc with beta status
