cmd/commit.go, cmd/dev.go, gittuf/commit.go, gittuf/git.go, gittuf/util.go, gittuf/verify.go
Targets some of the thoughts in #2.
=> Clean up Git interactions

cmd/commit.go, cmd/common.go, cmd/new_rule.go, docs/demo.md, gittuf/commit.go, gittuf/config.go, gittuf/new_rule.go, gittuf/util.go, gittuf/verify.go
https://github.com/adityasaky/gittuf/issues/13#issuecomment-1366985708
=> Make TUF metadata setup more opinionated

docs/specification.md
=> Update actor workflows

CHANGELOG.md, CONTRIBUTING.md, README.md, SECURITY.md
Also adds SECURITY.md, some edits to contributor workflow, and a badge from badgeapp.
=> Add initial changelog

internal/common/common.go, internal/gitinterface/commit.go, internal/gitinterface/commit_test.go, internal/gitinterface/common_test.go, internal/gitinterface/config.go, internal/gitinterface/keys.go, internal/gitinterface/keys_test.go, internal/gitinterface/tag.go, internal/gitinterface/tag_test.go, internal/gitinterface/utils.go
* Add general support for tags
* Generalizes signing / verifying operations in gitinterface, reusing code from commit signatures
=> Add support for tags

internal/cmd/root/root.go, internal/cmd/verifytag/verifytag.go, internal/common/common.go, internal/policy/helpers_test.go, internal/policy/policy.go, internal/policy/policy_test.go, internal/policy/targets_test.go, internal/policy/verify.go, internal/policy/verify_test.go, internal/repository/rsl_test.go, internal/repository/verify.go, internal/rsl/rsl.go, internal/rsl/rsl_test.go
Blocked until #101 is merged.
Addresses #15 #120
=> Add verify-tag

internal/rsl/rsl.go, internal/rsl/rsl_test.go
The change adding support for annotations to RSL functions (#129) didn't correctly handle looking for relevant annotations when an anchor was provided.
=> rsl: Look for annotations from latest entry

internal/cmd/version/version.go
#146 had code that made the linter unhappy after #148.
=> cmd: Fix lint issue

README.md
Temporarily update instructions to provide workaround for #151.
=> readme: Update install instructions

Makefile
- Added fmt target in the Makefile
- Changed install target prerequisite from test to build
=> Added fmt target in the Makefile

internal/gitinterface/blob.go, internal/gitinterface/tag.go, internal/gitinterface/tree.go
Fixes var name mistakes from #157
=> gitinterface: Fix var names

internal/gitinterface/changes.go, internal/gitinterface/changes_test.go
- Changed handling of merge commits to check if one of the parent commits matches the current commit
=> Handle Merge Commit in GetFilePathsChangedByCommit

internal/cmd/policy/policy.go, internal/cmd/trust/trust.go
=> fix: signing-key required on policy remote sub-commands.

internal/gitinterface/log_test.go
- Created test with a git tree containing a merge commit
- Added additional edge cases for regular git tree
=> Created test in log.go for merge commits

docs/design-document.md
This PR formalizes support for in-toto attestations in gittuf. It also defines reference authorizations to support threshold signing of reference state changes alongside RSL entries.
Supersedes #68, backs up #170
=> design: Formalize attestations

internal/policy/verify.go
=> Removed Misleading TODO

internal/gitinterface/tree.go, internal/gitinterface/tree_test.go
Pulled out from https://github.com/gittuf/gittuf/pull/170#discussion_r1388113362
=> gitinterface: Get all blob paths and IDs in tree

docs/design-document.md
This PR includes updates to the design doc to accompany #138. cc @wlynch
=> design: Flesh out recovery mmechanism

README.md
As it is not trivial to find the correct parameters to verify a release we should document them.
=> document how to verify released binary with cosign.

internal/cmd/root/root.go
This PR adds basic setup for logging with slog. And also adds '--verbose' flag for enabling debug level logging. (relevent: #54)
=> Add setup for logging with slog. Add 'verbose' flag for logging at debug level.

CHANGELOG.md
Updates changelog with a summary of key changes since v0.1.0.
=> Prepare v0.2.0 release

go.mod
- Upgrade golang 1.25.1 https://go.dev/doc/devel/release#go1.21.minor
=> Upgrade golang 1.21.5

go.mod, go.sum, internal/attestations/attestations.go, internal/attestations/attestations_test.go, internal/attestations/authorization.go, internal/attestations/authorization_test.go
This PR adds the basic plumbing for attestations from #164.
=> attestations: Add plumbing for attestations

internal/cmd/policy/listrules/listrules.go, internal/cmd/policy/policy.go, internal/policy/helpers_test.go, internal/policy/policy.go, internal/policy/policy_test.go, internal/repository/policy.go
- Added the list-rules command, which list all current rules for the latest policy state.
- Fixes issue #191
=> Added list-rules to cmd

internal/cmd/common/common.go, internal/cmd/policy/addkey/addkey.go, internal/cmd/policy/addrule/addrule.go, internal/cmd/trust/addpolicykey/addpolicykey.go, internal/cmd/trust/addrootkey/addrootkey.go, internal/tuf/test-data/test-key.pem, internal/tuf/tuf.go, internal/tuf/tuf_test.go
=> Add support for loading PEM encoded keys into policy

docs/cli/gittuf_policy_add-key.md, docs/cli/gittuf_policy_add-rule.md, docs/cli/gittuf_policy_init.md, docs/cli/gittuf_policy_remove-rule.md, docs/cli/gittuf_policy_sign.md, internal/cmd/policy/addkey/addkey.go, internal/cmd/policy/addrule/addrule.go, internal/cmd/policy/init/init.go, internal/cmd/policy/removerule/removerule.go, internal/cmd/policy/sign/sign.go
Address https://github.com/gittuf/gittuf/pull/270#discussion_r1453982535
=> cmd: Clarify help message for policy file flags

.github/workflows/ci.yml, LICENSE, README.md, docs/design-document.md, docs/get-started.md
~Draft until I also add the get started guide.~
~LMK if the logo in the readme is too much.~ Now at 25% width.
=> docs: Add logo, update year in license, add get started guide

internal/policy/verify.go, internal/repository/hook.go, internal/repository/policy.go, internal/repository/repository.go, internal/repository/root.go, internal/repository/rsl.go, internal/repository/sync.go, internal/repository/targets.go, internal/repository/verify.go
This PR takes over #249.
It's possible I'm misusing the slog format here...
=> Add debug log statements

docs/design-document.md
1. Added a visual representation of a Git repository structure.
2. Expanded the definition of 'Actors' in the context of a Git repository and the gittuf system.
3. Introduced a new term 'State' and provided a detailed explanation and example of it.
=> Enhance Documentation - Design

internal/policy/policy.go, internal/policy/verify.go
~Pulling some early ideas together.~
This PR adds a cache for verifiers identified for some path in a specific policy state.
=> policy: Add caching

internal/gitinterface/tree.go, internal/policy/verify.go, internal/policy/verify_test.go, internal/repository/attestations.go
Various things I'm running into as I'm kicking the tyres of #336.
=> Fixes / debug statements in gittuf dev authorize

internal/cmd/policy/listrules/listrules.go, internal/repository/sync.go, internal/repository/verify.go
gittuf clone does not currently clone the attestations ref. This PR fixes that.
=> repository: Clone attestations

internal/repository/rsl.go
=> Fixed typo

internal/policy/policy.go, internal/policy/policy_test.go, internal/rsl/rsl.go, internal/rsl/rsl_test.go
- Created a helper function that is almost the same as GetFirstEntry, but with an expected targetRef
=> Changed LoadState to not assume that the first entry is for the policy ref

docs/dogfood.md, docs/get-started.md
Add pushing and pulling gittuf to dogfooding docs
=> Add pushing and pulling gittuf to dogfooding docs

docs/cli/gittuf_clone.md, internal/cmd/clone/clone.go, internal/cmd/common/common.go, internal/policy/policy.go, internal/policy/policy_test.go, internal/repository/sync.go, internal/repository/sync_test.go
- Added the expectedRootKeys flag to clone.go
- Added additional test in sync_test.go for expectedRootKeys
Signed-off-by: neilnaveen [42328488+neilnaveen@users.noreply.github.com](mailto:42328488+neilnaveen@users.noreply.github.com)
=> Add expected root keys flag for cloning 

docs/cli/gittuf_rsl.md, docs/cli/gittuf_rsl_log.md, internal/cmd/rsl/log/log.go, internal/cmd/rsl/rsl.go, internal/display/display.go, internal/display/display_test.go, internal/display/rsl.go, internal/display/rsl_test.go, internal/policy/policy.go, internal/repository/rsl.go, internal/repository/rsl_test.go
- Added gittuf rsl log to log the rsl with additional information
- Changed list-rules to accept a RSL entry to list rules at the RSL entries state
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> Added gittuf rsl log to log the rsl with additional information

internal/gitinterface/commit.go, internal/gitinterface/commit_test.go, internal/gitinterface/common.go, internal/gitinterface/references.go, internal/gitinterface/references_test.go, internal/gitinterface/repository.go, internal/gitinterface/signature.go, internal/gitinterface/tag.go, internal/gitinterface/tag_test.go, internal/gitinterface/tree.go, internal/gitinterface/tree_test.go, internal/gitinterface/utils.go, internal/policy/verify.go
These are a little intertwined, so I'm submitting them together.
=> gitinterface: Add support for trees, commits, tags, and references

MAINTAINERS.txt
On the recommendation of @adityasaky.
=> Add @patzielinski as a maintainer

internal/gitinterface/blob.go, internal/gitinterface/blob_test.go, internal/gitinterface/changes.go, internal/gitinterface/changes_test.go, internal/gitinterface/commit.go, internal/gitinterface/commit_test.go, internal/gitinterface/common.go, internal/gitinterface/config.go, internal/gitinterface/config_test.go, internal/gitinterface/log.go, internal/gitinterface/log_test.go, internal/gitinterface/references.go, internal/gitinterface/references_test.go, internal/gitinterface/repository.go, internal/gitinterface/sync.go, internal/gitinterface/sync_test.go, internal/gitinterface/tag.go, internal/gitinterface/tag_test.go, internal/gitinterface/tree.go, internal/gitinterface/tree_test.go, internal/gitinterface/utils.go
This is the final part of #367. This still needs tests.
=> Add change / config / sync for gitinterface with binary

MAINTAINERS.txt
- https://github.com/gittuf/gittuf/issues/459
=> Add @neilnaveen as a maintainer

CHANGELOG.md
=> Prepare v0.5.0 release

CHANGELOG.md
=> Prepare v0.5.2 release

.golangci.yml, internal/repository/attestations.go
=> repository: Support enterprise GH with GitHub client

internal/policy/policy_test.go, internal/policy/verify_test.go, internal/rsl/rsl_test.go
Trying to speed up tests
@patzielinski
=> speed up windows tests

.github/workflows/coverage.yml, .test_ignore.txt, README.md
Testing uploading coverage to coveralls.
=> ci: Add upload to coveralls

CHANGELOG.md
This PR  adds the changelog for and prepares `v0.6.0`.
=> Prepare v0.6.0 release

.test_ignore.txt, Makefile, internal/gittuf-git/args/args.go, internal/gittuf-git/args/args_test.go, internal/gittuf-git/cmd/cmd.go, internal/gittuf-git/main.go
Added Git command to the root command.
=> Git command compatibility #220

internal/git-remote-gittuf/curl.go
git-remote-gittuf wasn't handling fetches correctly on windows with the curl backend because the response from the server was preceded by an extra buffer containing just a newline character.
=> transport: Fix curl fetches on Windows

internal/git-remote-gittuf/curl.go
counterpart to #569 on the push side of things.
=> transport: Fix curl pushes on Windows

internal/git-remote-gittuf/curl.go, internal/git-remote-gittuf/ssh.go
When refs/gittuf/ refs are explicitly pushed, we don't correctly send the result of the push back to the caller. This can cause pushes to hang. This commit tracks the refs that are explicitly set to be pushed to identify which status messages to send back to the caller.
=> transport: Improve explicit pushes of refs/gittuf/ refs

internal/git-remote-gittuf/ssh.go
=> transport: Handle explicit RSL push in ssh

internal/repository/root.go, internal/signerverifier/sigstore/sigstore.go
=> *: Allow use of Sigstore for root metadata

CHANGELOG.md
=> Prepare v0.7.0

docs/cli/gittuf_policy.md, docs/cli/gittuf_policy_add-key.md, docs/cli/gittuf_policy_add-person.md, docs/cli/gittuf_policy_add-rule.md, docs/cli/gittuf_policy_update-rule.md, docs/get-started.md, docs/testing/tester-expected-unix.txt, docs/testing/tester-expected-win.txt, experimental/gittuf/helpers_test.go, experimental/gittuf/targets.go, experimental/gittuf/targets_test.go, internal/cmd/policy/addkey/addkey.go, internal/cmd/policy/addperson/addperson.go, internal/cmd/policy/addrule/addrule.go, internal/cmd/policy/policy.go, internal/cmd/policy/updaterule/updaterule.go, internal/policy/helpers_test.go, internal/policy/policy_test.go, internal/tuf/tuf.go, internal/tuf/v01/targets.go, internal/tuf/v01/targets_test.go, internal/tuf/v02/targets.go, internal/tuf/v02/targets_test.go
=> Expose persons / principals in CLI

docs/cli/gittuf_dev_add-github-approval.md, docs/cli/gittuf_dev_dismiss-github-approval.md, experimental/gittuf/attestations.go, experimental/gittuf/attestations_test.go, internal/attestations/github.go, internal/attestations/github/github.go, internal/attestations/github/v01/approval.go, internal/attestations/github/v01/approval_test.go, internal/attestations/github_test.go, internal/cmd/dev/addgithubapproval/addgithubapproval.go, internal/cmd/dev/dismissgithubapproval/dismissgithubapproval.go, internal/common/set/set.go, internal/policy/helpers_test.go, internal/policy/verify.go, internal/policy/verify_test.go
This PR updates the verification workflow to use identities defined by the code review tool and declared for a "person".
=> *: Use person associatedIdentities to verify code review tool approvals

internal/policy/verify.go
This is trying to formalize some assumptions we make in the verification flow. I plan to add some of these continuously, with a focus on the verification flow.
=> policy: Add some explicit assumptions in verification flow

internal/git-remote-gittuf/curl.go, internal/git-remote-gittuf/ssh.go
Per comment from @patzielinski
=> transport: Add explanation for wroteGittufWantsAndHaves

internal/git-remote-gittuf/curl.go, internal/git-remote-gittuf/ssh.go
On pushes, we weren't bubbling up the status of pushed ref correctly because the `dstRefs` check included a trailing newline. This fixes that.
Now:
```
...
To gittuf::github:gittuf/gittuf
* [new branch]      fix-transport-push-status -> fix-transport-push-status
```
Before:
```
...
Writing objects: 100% (6/6), 990 bytes | 990.00 KiB/s, done.
Total 6 (delta 5), reused 0 (delta 0), pack-reused 0
Everything up-to-date
```
=> transport: Fix server response on push

experimental/gittuf/repository_test.go
=> gittuf: Improve testing coverage

internal/rsl/rsl_test.go
Linked to: https://github.com/gittuf/gittuf/issues/557
This PR is part of a larger effort to improve the coverage of the codebase
Before coverage `internal/rsl` package %age: 83.2%
After coverage `internal/rsl` %age: 83.9%
Attaching the coverage report for reference as a zip(apparently Github doesn't allow .out format attachments): 
[finalcoverage.out.zip](https://github.com/user-attachments/files/17684214/finalcoverage.out.zip)
=> add two new unit test cases

internal/git-remote-gittuf/curl.go
This seems like a partial fix for the clone issue.
FWIW, with this in place, I'm still seeing an `update-ref` failure to _use_ the rsl tip object, but the object itself is fetched. I'm half wondering if this is a race condition with the unpacking.
=> transport: Handle 'done' during fetches

CHANGELOG.md, docs/get-started.md
~~Blocked by #676.~~
~~Blocked by #679.~~
This PR prepares gittuf `v0.8.0`.
=> Prepare v0.8.0

.github/workflows/run-demo.yml
- Add run-demo.py checks workflow
=> workflows: Run demo workflow

.github/workflows/run-demo.yml
=> ci: Set permissions for run-demo

docs/design-document.md, docs/extensions/authentication-evidence-attestations.md, docs/extensions/gittuf-on-the-forge.md, docs/extensions/hash-algorithm-agility.md
This cleans up various parts of the design document, including updating it to reflect some changes. The document now also points to the accepted NDSS paper.
=> docs: Major reworking of design document

internal/cache/attestations.go, internal/cache/cache.go, internal/cache/policy.go, internal/policy/searcher.go
This is a continuation of the persistent cache work.
=> Maintain persistent cache

docs/cli/gittuf_dev.md, docs/cli/gittuf_dev_populate-cache.md, experimental/gittuf/cache.go, experimental/gittuf/cache_test.go, internal/cache/attestations.go, internal/cache/cache.go, internal/cache/policy.go, internal/cache/verification.go, internal/cmd/dev/dev.go, internal/cmd/dev/populatecache/populatecache.go, internal/policy/policy.go, internal/policy/searcher.go, internal/policy/searcher_test.go, internal/policy/verify.go
This commit adds support for persistent cache searching as well as explicit populating.
=> Use persistent cache

internal/policy/verify.go
We have two very similar helpers: verifyGitObjectAndAttestations and verifyGitObjectAndAttestationsUsingVerifiers. The first one calls the second one. However, there were numerous cases of direct invocation of the second one. This commit makes the first helper the one that's used consistently. This ensures that finding which verifiers to use and so on are consistent everywhere.
=> policy: Streamline verification helper

docs/cli/gittuf_trust.md, docs/cli/gittuf_trust_add-global-rule.md, experimental/gittuf/root.go, experimental/gittuf/root_test.go, internal/cmd/trust/addglobalrule/addglobalrule.go, internal/cmd/trust/trust.go, internal/policy/helpers_test.go, internal/policy/policy.go, internal/policy/signature.go, internal/policy/verify.go, internal/policy/verify_test.go, internal/tuf/tuf.go, internal/tuf/v01/root.go, internal/tuf/v01/root_test.go, internal/tuf/v01/targets.go, internal/tuf/v01/targets_test.go, internal/tuf/v02/root.go, internal/tuf/v02/root_test.go, internal/tuf/v02/targets.go, internal/tuf/v02/targets_test.go
This is a WIP PR adding initial support for "global rules" that set baselines that must be met during verification.
=> Add support for global rules

docs/cli/gittuf_trust.md, docs/cli/gittuf_trust_set-repository-location.md, experimental/gittuf/options/root/root.go, experimental/gittuf/root.go, experimental/gittuf/root_test.go, internal/cmd/trust/setrepositorylocation/setrepositorylocation.go, internal/cmd/trust/trust.go, internal/tuf/migrations/migrations.go, internal/tuf/tuf.go, internal/tuf/v01/root.go, internal/tuf/v01/root_test.go, internal/tuf/v02/root.go, internal/tuf/v02/root_test.go
=> *: Add repositoryLocation to root metadata

docs/gaps/4/README.md
Taken from #638. I suggest we merge this while we iterate rather than have it be a long lived open PR. We can iterate through the issue tracker and edit PRs.
=> docs: Add global constraints GAP

internal/gitinterface/tree.go, internal/gitinterface/tree_test.go
This is a subset of #758 with changes to gitinterface.
=> gitinterface: Add APIs for inspecting trees

internal/tuf/migrations/migrations.go, internal/tuf/tuf.go, internal/tuf/v01/root.go, internal/tuf/v01/root_test.go, internal/tuf/v02/root.go, internal/tuf/v02/root_test.go
This is the first in a sequence of PRs for adding multi-repo policies in gittuf.
=> tuf: Add support for multi-repository policies

CHANGELOG.md
This PR prepares gittuf `v0.9.0`.
=> Prepare v0.9.0

internal/tuf/tuf.go, internal/tuf/v01/root_test.go, internal/tuf/v02/root_test.go
This PR fixes some issues found after running `golangci-lint` locally.
=> tuf: Fix issues raised by linter

docs/cli/gittuf.md, docs/cli/gittuf_sync.md, experimental/gittuf/rsl.go, experimental/gittuf/rsl_test.go, internal/cmd/root/root.go, internal/cmd/sync/sync.go, internal/gitinterface/sync.go
=> *: Add gittuf sync

docs/cli/gittuf_trust.md, docs/cli/gittuf_trust_list-global-rules.md, experimental/gittuf/root.go, experimental/gittuf/root_test.go, internal/cmd/trust/listglobalrules/listglobalrules.go, internal/cmd/trust/trust.go
=> gittuf: add command list-globalrules

.test_ignore.txt, go.mod, go.sum, internal/luasandbox/main.go
This PR adds the lua sandbox environment to gittuf, in order to be able to run GUPPIEs in an isolated environment.
Part of a series, more to come.
cc @fr0m-scratch
=> [GUPPIEs] lua-sandbox: Add a lua sandbox for running GUPPIEs

.github/workflows/gittuf-rsl-main.yml, .github/workflows/gittuf-rsl-non-main.yml
=> ci: Update how gittuf metadata is recorded

internal/luasandbox/luasandbox.go
This breaks away my improvements from #859.
=> luasandbox: Add environment wrapper type

.gitattributes, .test_ignore.txt, docs/cli/main.go, docs/sandbox/README.md, docs/sandbox/main.go, internal/luasandbox/apis.go, internal/luasandbox/luasandbox.go
This PR takes a stab at structuring how APIs can be added / registered for the sandbox. It also adds some very basic APIs.
=> sandbox: Add stucture for API creation and registration

.github/workflows/ci-locale.yml, internal/gitinterface/repository.go
=> gitinterface: Ensure git output is in english

docs/cli/gittuf_trust.md, docs/cli/gittuf_trust_add-hook.md, docs/cli/gittuf_trust_list-hooks.md, docs/cli/gittuf_trust_remove-hook.md, experimental/gittuf/policy.go, experimental/gittuf/root.go, experimental/gittuf/root_test.go, internal/cmd/trust/addhook/addhook.go, internal/cmd/trust/listhooks/listhooks.go, internal/cmd/trust/removehook/removehook.go, internal/cmd/trust/trust.go, internal/gitinterface/hash.go, internal/policy/policy.go, internal/testartifacts/scripts.go, internal/testartifacts/testdata/scripts/hello.lua, internal/tuf/tuf.go, internal/tuf/v01/root.go, internal/tuf/v01/root_test.go, internal/tuf/v02/root.go, internal/tuf/v02/root_test.go
This PR adds functionality to manage GUPPIEs.
~~Blocked by #815.~~
=> [GUPPIEs] *: Add management functionality for GUPPIEs

docs/cli/gittuf_trust.md, docs/cli/gittuf_trust_add-controller-repository.md, docs/cli/gittuf_trust_add-network-repository.md, docs/cli/gittuf_trust_make-controller.md, experimental/gittuf/root.go, internal/cmd/trust/addcontrollerrepository/addcontrollerrepository.go, internal/cmd/trust/addnetworkrepository/addnetworkrepository.go, internal/cmd/trust/makecontroller/makecontroller.go, internal/cmd/trust/trust.go
Possibly the last bit of #808?
=> *: Add APIs for controller / network repo management

internal/policy/policy.go, internal/policy/verify.go
=> Apply controller global rules

internal/policy/policy.go, internal/policy/verify_test.go
In adding this test, a bug was discovered in the ordering / logic of FindVerifiersForPath. This commit also fixes it so that global rules are prioritized for now.
=> policy: Add test for global rules verification

docs/gaps/README.md
Quick PR to add a list of GAPs
=> docs: Add list of GAPs

docs/design-document.md
This fixes a minor deviation in the design doc.
=> docs: Update RSL entry schemas to reflect implementation

internal/tuf/tuf.go, internal/tuf/v01/root.go, internal/tuf/v01/root_test.go, internal/tuf/v02/root.go, internal/tuf/v02/root_test.go
fixes: https://github.com/gittuf/gittuf/issues/804#issuecomment-2648739175
=> added Duplication check

experimental/gittuf/policy.go
Fixed `ListHooks` function in the gittuf package
=> policy: fix `ListHooks` function

SECURITY_INSIGHTS.yml
This PR adds the `SECURITY_INSIGHTS.yml` file as raised in #748.
Closes #748.
=> Add SECURITY_INSIGHTS.yml

docs/cli/gittuf_policy_add-rule.md, experimental/gittuf/helpers_test.go, experimental/gittuf/targets.go, experimental/gittuf/targets_test.go, internal/cmd/policy/addrule/addrule.go, internal/cmd/policy/tui/tui.go, internal/cmd/policy/updaterule/updaterule.go, internal/policy/helpers_test.go, internal/policy/policy_test.go, internal/tuf/tuf.go, internal/tuf/v01/targets.go, internal/tuf/v01/targets_test.go, internal/tuf/v02/targets.go, internal/tuf/v02/targets_test.go
Added read/write access flag to targets metadata
=> [WIP] Add read write 

docs/roadmap.md
This updates the roadmap document.
=> docs: Update roadmap

.github/workflows/coverage.yml
add an additional filter line in the coverage workflow to remove individual files
=> fix test coverage filters to also remove individual files

internal/cmd/policy/tui/tui.go
Implements the new global‑rule feature and fixes #898
=> add global rule support for TUI

experimental/gittuf/policy.go, experimental/gittuf/policy_test.go
Add an API to check if a repository has a gittuf policy applied.
=> gittuf: Add HasPolicy method

CHANGELOG.md
=> Prepare v0.10.1

experimental/gittuf/attestations.go, experimental/gittuf/options/github/github.go
Per a suggestion from @wlynch to try and get rid of intermittent token expiry issues.
=> *: Accept token source for interacting with the GitHub API

CHANGELOG.md
Cut a quick release to benefit from #998.
=> Prepare v0.10.2

.github/workflows/gittuf-verify.yml
Should fix the Scorecard alert for the token item.
=> ci: Set workflow permission for gittuf-verify.yml

README.md
Adds a scorecard badge to the README.
=> docs: Add scorecard badge to README

README.md, docs/design-document.md
https://github.com/ossf/tac/pull/486 has been merged and gittuf is now an incubating project. :)
=> docs: sandbox -> incubating

internal/gitinterface/sync.go
This is a quick stab at supporting shallow fetches in gitinterface. This should reduce the memory requirements when used in the github app as well as generally make it faster.
=> gitinterface: Support shallow fetches

MAINTAINERS.txt
@adityasaky :slightly_smiling_face:
=> Update maintainer affiliation
